name: client_app
description: Ruben and Katie Wedding App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.12.0
  flutter_bloc: 6.0.0
  freezed_annotation: 0.11.0
  url_launcher: 5.5.0
  kt_dart: 0.7.0+1
  auto_route: ^0.6.6
  get_it: ^4.0.4
  dartz: 0.9.1
  equatable: ^1.2.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  injectable: ^1.0.2
  build_context: 2.0.4
  font_awesome_flutter: 8.8.1
  hexcolor: ^1.0.4
  flutter_vector_icons: 0.2.1
  google_fonts: ^1.1.0
  flushbar: 1.10.4
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  freezed: 0.11.4
  build_runner: ^1.10.0
  injectable_generator: ^1.0.2
  auto_route_generator: ^0.6.6

flutter:
  uses-material-design: true
