name: wedding_app
description: Ruben and Katie Wedding App
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.14.1
  flutter_bloc: 6.0.6
  freezed_annotation: 0.12.0
  url_launcher: 5.7.5
  kt_dart: 0.8.0
  auto_route: ^0.6.9
  get_it: 5.0.1
  dartz: 0.9.2
  equatable: ^1.2.5
  firebase_core: ^0.5.0+1
  build_context: ^2.0.4
  font_awesome_flutter: 8.10.0
  google_fonts: ^1.1.1
  flushbar: 1.10.4
  uuid: ^2.2.2
  cloud_firestore: ^0.14.1+3
  json_annotation: ^3.1.0
  auto_size_text: ^2.1.0
  carousel_slider: 2.3.1
  pinch_zoom_image_last: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  freezed: 0.12.2
  build_runner: ^1.10.1
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.0
  flutter_launcher_icons: 0.8.1
  flutter_native_splash: 0.1.9

# flutter pub run change_app_package_name:main com.ferdzz.weddingapp
  change_app_package_name: 0.1.2

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/circle_launcher.png"
  adaptive_icon_background: "#6D8474"
  android: true
  ios: true

# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash.png
  color: "FFFFFF"

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/molenvliet/
  fonts:
    - family: Castellar
      fonts:
        - asset: assets/fonts/CASTELAR.ttf
    - family:  WeddingApp
      fonts:
      - asset: assets/fonts/WeddingApp.ttf
