name: widgets
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hex_color: 1.0.2
  cupertino_icons: ^0.1.3
  font_awesome_flutter: 8.8.1
  google_fonts: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
